### PR TITLE
Updated model in sync with PAL local package.

### PR DESCRIPTION
**Pull request by awesomebytes**
- Separated a part of the launch in reemc_bringup.launch
- Added config dir on install
- cmfDamping -> implicitSpringDamper
- Removed collision groups (not supported).
- Updated copyrights.
- Updated some params slightly.

### CODE REVIEW

**Comment by efernandez** [comment]
I identify a few changes I made here, internally.
There is quite a good number of atomic commits for them in our internal repo. Don't whether it's easy to keep it here or not. @po1 

There are also other stuff in this mega-commit I don't know. @bmagyar

**Comment by awesomebytes** [comment]
I tested this changes in an external computer. I needed to add to the .rosinstall file of reemc simulation pal_gazebo_plugins.

Worked well.

**Comment by po1** [comment]
It's not that hard to try to get the atomic commits.
@efernandez you just have to overlay a `git-svn` on top of the svn checkout, add the github remote and rebase/cherry-pick the commits.
@awesomebytes please ask somebody not oo busy from the Nav team for more instructions

**Comment by awesomebytes** [comment]
I lost too much time with this. I'm not able to cherry pick all the changes fixing every conflict.
This is "just" the public version which I already tested on my machine and an external machine and it works, reemc launches in gazebo, you can launch the controllers, move the robot with play_motion, topics are there...

In our local svn there are all the commits if something breaks. And if something is not working in the public release, as far as I know, I'll be blamed and I'll fix it as the main audience using it is Robocup/Rockin/Humabot participants.

**Comment by po1** [comment]
As long as you keep your promise of fixing it when it breaks, I'm good.
+1

**Comment by awesomebytes** [comment]
Yeah, I'll do my best!

**Comment by bmagyar** [comment]
@awesomebytes I've seen a reference to pal_hand gazebo plugin. It might make sense to also check that

**Comment by bmagyar** [comment]
btw, it looks good to me

**Comment by awesomebytes** [comment]
pal_gazebo_plugins (where the pal_hand_gazebo plugin is) it's only on github and has not had any change so it's good.

**Comment by po1** [comment]
Let's go then.

**Pull request merged**
